module FinchLogic
    using RewriteTools, SyntaxInterface, AbstractTrees, Finch
    using Finch: virtualize, freshen

    export logic_leaf
    export literal
    export index
    export variable
    export value
    export access
    export define
    export mapped
    export reduced
    export reorder
    export reformat
    export result
    export evaluate
    export LogicNode

    export isliteral, isvalue, isvariable, isindex

    export isprotocol

    include("nodes.jl")
    #include("instances.jl") #This file was generated by chatgpt, may need to be fixed before use
    #include("virtualize.jl") #This file was generated by chatgpt, may need to be fixed before use
end
