module FinchLogic
    using RewriteTools, SyntaxInterface, AbstractTrees, Finch
    using Finch: virtualize, freshen

    export logic_leaf
    export literal
    export field
    export alias
    export value
    export table
    export subquery
    export mapjoin
    export aggregate
    export reorder
    export reformat
    export result
    export evaluate
    export LogicNode

    export isliteral, isvalue, isalias, isfield

    export isprotocol

    include("nodes.jl")
    #include("instances.jl") #This file was generated by chatgpt, may need to be fixed before use
    #include("virtualize.jl") #This file was generated by chatgpt, may need to be fixed before use
end
